"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
import Nav from "../../components/Nav";
import type { Analysis, Message, SocraticResponse } from "../../api/socratic/route";

type Subject = "circuits" | "calculus" | "chemistry" | "biology" | "mechanics" | "algebra";

const CONFIGS: Record<Subject, {
  label: string;
  name: string;
  problem: string;
  starter: string;
  photo: string;
}> = {
  circuits: {
    label: "Physics",
    name: "Electric Circuits",
    problem: 'A 12V battery is connected to two resistors in series: R1 = 3Ω and R2 = 6Ω. A student claims the current through R2 is smaller than through R1 because "some electricity gets used up by R1." What is wrong with this reasoning?',
    starter: "I think the current does get smaller after R1. R1 uses up some of the electricity, so there's less left for R2.",
    photo: "/subjects/circuits.jpg",
  },
  calculus: {
    label: "Calculus",
    name: "Derivatives",
    problem: "For f(x) = x², a student evaluates the function at x = 3 and gets f(3) = 9. They say \"the derivative at x = 3 is also 9, because I just plug in x = 3.\" What is the misconception?",
    starter: "I think the derivative at x = 3 is 9, since f(3) = 3² = 9. That's what I get when I substitute.",
    photo: "/subjects/calculus.jpg",
  },
  chemistry: {
    label: "Chemistry",
    name: "Stoichiometry",
    problem: "For the reaction 2H₂ + O₂ → 2H₂O, a student has 4 mol H₂ and 3 mol O₂. They say \"O₂ is the limiting reactant because we have fewer moles of it.\" Is this correct?",
    starter: "O₂ must be limiting because 3 mol is less than 4 mol, so we'll run out of O₂ first.",
    photo: "/subjects/chemistry.jpg",
  },
  biology: {
    label: "Biology",
    name: "Cell Osmosis",
    problem: "A red blood cell is placed in a saltwater solution. A student says: \"Water moves out of the cell because salt attracts water and pulls it across the membrane.\" What is wrong with this explanation?",
    starter: "Salt attracts water molecules, so it pulls the water out of the cell and into the salty solution. That's why the cell shrinks.",
    photo: "/subjects/biology.jpg",
  },
  mechanics: {
    label: "Mechanics",
    name: "Newton's Laws",
    problem: "A truck collides with a small bug on the highway. A student claims: \"The truck exerts a much larger force on the bug than the bug exerts on the truck, because the truck is so much bigger and heavier.\" Is this correct?",
    starter: "Obviously the truck pushes on the bug way harder — the truck is massive and the bug weighs almost nothing. The forces can't be equal.",
    photo: "/subjects/mechanics.jpg",
  },
  algebra: {
    label: "Algebra",
    name: "Quadratic Functions",
    problem: "For the equation x² - 5x + 6 = 0, a student says: \"I can see the answer is x = 5 or x = 6 just by looking at the numbers in the equation.\" What is the misconception here?",
    starter: "The equation has -5x and +6, so the roots must be x = 5 and x = 6. I can just read them off.",
    photo: "/subjects/algebra.jpg",
  },
};

function downloadPDF(msgs: ChatMsg[], subjectName: string, subject: string) {
  const lines: string[] = [];
  lines.push(`LabLens — Learning Session Report`);
  lines.push(`Subject: ${subjectName}`);
  lines.push(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  lines.push(`Powered by Featherless.ai · Qwen2.5-72B`);
  lines.push(`${"─".repeat(60)}`);
  lines.push(``);

  msgs.forEach((msg, i) => {
    const who = msg.role === "assistant" ? "LabLens AI" : "You";
    lines.push(`[${i + 1}] ${who}`);
    lines.push(msg.content);
    if (msg.analysis) {
      if (msg.analysis.misconception) lines.push(`  ⚠ Misconception detected: ${msg.analysis.misconception}`);
      lines.push(`  Progress: ${msg.analysis.progress}/5`);
      lines.push(`  Next move: ${msg.analysis.next_move}`);
      if (msg.analysis.teacher_note) lines.push(`  Note: ${msg.analysis.teacher_note}`);
    }
    lines.push(``);
  });

  lines.push(`${"─".repeat(60)}`);
  lines.push(`Generated by LabLens AI Socratic Tutor`);
  lines.push(`Session ID: ${subject}-${Date.now()}`);

  const content = lines.join("\n");
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `LabLens-${subjectName.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}


function isValidSubject(s: string): s is Subject {
  return ["circuits", "calculus", "chemistry", "biology", "mechanics", "algebra"].includes(s);
}

type ChatMsg = {
  role: "user" | "assistant";
  content: string;
  analysis?: Analysis;
  source?: "featherless" | "fallback";
};

const MOVE_MAP: Record<string, string> = {
  probe_deeper: "Probing deeper",
  challenge_analogy: "Challenging with analogy",
  affirm_progress: "Affirming progress",
  confirm_understanding: "Understanding confirmed",
};

const PROGRESS_LABELS = ["No engagement", "Engaging", "Probing", "Connecting", "Almost there", "Understood ✓"];

export default function TutorPage() {
  const params = useParams();
  const rawSubject = params.subject as string;
  const subject = isValidSubject(rawSubject) ? rawSubject : "circuits";
  const config = CONFIGS[subject];

  const [msgs, setMsgs] = useState<ChatMsg[]>([]);
  const [input, setInput] = useState(config.starter);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const lastAnalysis = msgs.filter((m) => m.analysis).at(-1)?.analysis ?? null;
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [msgs, loading]);

  async function send(e?: FormEvent) {
    e?.preventDefault();
    const text = input.trim();
    if (!text || loading || done) return;

    const userMsg: ChatMsg = { role: "user", content: text };
    const next = [...msgs, userMsg];
    setMsgs(next);
    setInput("");
    setLoading(true);

    try {
      const apiMsgs: Message[] = next.map((m) => ({ role: m.role, content: m.content }));
      const res = await fetch("/api/socratic", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: apiMsgs, subject }),
      });
      const data: SocraticResponse = await res.json();
      setMsgs([...next, { role: "assistant", content: data.reply, analysis: data.analysis, source: data.source }]);
      if (data.analysis.progress >= 5 || data.analysis.next_move === "confirm_understanding") {
        setDone(true);
      }
    } catch {
      setMsgs([...next, { role: "assistant", content: "Connection error — please try again." }]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <Nav />

      <div className="tutor-page">
        <div className="tutor-hero">
          <div className="tutor-hero-bg" style={{ backgroundImage: `url(${config.photo})` }} />
          <div className="tutor-hero-body">
            <span className="eyebrow">{config.label}</span>
            <h1>{config.name}</h1>
            <p>The AI will guide you with questions — not answers. Explain your reasoning honestly.</p>
          </div>
        </div>

        <div className="problem-card">
          <span className="eyebrow">The Problem</span>
          <p>{config.problem}</p>
        </div>

        <div className="chat-thread">
          {msgs.length === 0 && (
            <div className="chat-empty">
              Write your initial reasoning below.<br />
              Be honest — wrong answers lead to the best learning.
            </div>
          )}

          {msgs.map((msg, i) => (
            <div key={i} className={`chat-msg ${msg.role}`}>
              <div className="chat-msg-header">
                <div className={`chat-avatar ${msg.role === "assistant" ? "ai" : ""}`}>
                  {msg.role === "assistant" ? "L" : "Y"}
                </div>
                <span className="chat-who">{msg.role === "assistant" ? "LabLens AI" : "You"}</span>
              </div>
              <div className="chat-msg-body">{msg.content}</div>

              {msg.analysis && (
                <div className="cognitive-annotation">
                  {msg.analysis.misconception && (
                    <span className="cog-chip warn">
                      <span className="cog-dot" />
                      {msg.analysis.misconception}
                    </span>
                  )}
                  <span className={`cog-chip ${msg.analysis.progress >= 4 ? "good" : ""}`}>
                    Progress: {PROGRESS_LABELS[msg.analysis.progress]}
                  </span>
                  {msg.analysis.next_move && (
                    <span className="cog-chip">
                      {MOVE_MAP[msg.analysis.next_move] ?? msg.analysis.next_move}
                    </span>
                  )}
                </div>
              )}
              {msg.source && (
                <div className="source-tag">
                  via {msg.source === "featherless" ? "Featherless.ai · Qwen2.5-72B" : "local fallback"}
                </div>
              )}
            </div>
          ))}

          {loading && (
            <div className="chat-msg assistant">
              <div className="chat-msg-header">
                <div className="chat-avatar ai">L</div>
                <span className="chat-who">LabLens AI</span>
              </div>
              <div className="chat-msg-body">
                <div className="typing-dots">
                  <span /><span /><span />
                </div>
              </div>
            </div>
          )}

          {done && (
            <div className="session-done">
              <h3>Session complete.</h3>
              <p>
                {lastAnalysis?.teacher_note ?? "You've worked through the misconception. The understanding is yours now."}
              </p>
              <div className="session-done-actions">
                <Link href="/subjects">Try another subject →</Link>
                <button onClick={() => downloadPDF(msgs, config.name, subject)}>⬇ Download PDF report</button>
              </div>
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        <div className="chat-bottom-spacer" />
      </div>

      {!done && (
        <div className="chat-input-area">
          <form className="chat-input-inner" onSubmit={send}>
            <textarea
              className="chat-input"
              rows={2}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); }
              }}
              placeholder="Explain your reasoning… (Enter to send, Shift+Enter for new line)"
            />
            <button className="send-btn" type="submit" disabled={loading || !input.trim()}>
              {loading ? "…" : "Send"}
            </button>
          </form>
        </div>
      )}
    </>
  );
}
